### ISSUE TITLE
Application Error When Paypal Redirects Back To My App

### ISSUE THREAD

**Issue by AirGuitar** [laurenceputra/smu-paypal-2015#1]
Hi Laurence!

I've tried implementing the payment app and when it redirects back to my application it throws me an error stating - Application Error - An error occurred in the application and your page could not be served.
My URL-
~/payment/execute?token=EC-6NW454274S0406157
is something wrong?

Brandon

**Comment by laurenceputra** [comment]
can you install the [toolbelt](https://toolbelt.heroku.com/debian) and run `heroku logs` and paste your logs here?

it is working fine on my end

**Comment by AirGuitar** [comment]
![heroku logs 4](https://cloud.githubusercontent.com/assets/11301163/6485938/477d370c-c2c2-11e4-969b-9609222e30a1.JPG)
![heroku logs 1](https://cloud.githubusercontent.com/assets/11301163/6485939/47815472-c2c2-11e4-923f-077e6b44fb6a.JPG)
![heroku logs 2](https://cloud.githubusercontent.com/assets/11301163/6485940/47889b74-c2c2-11e4-9837-479023e593e2.JPG)
![heroku logs 3](https://cloud.githubusercontent.com/assets/11301163/6485941/4794d4c0-c2c2-11e4-9958-4b5a545aed85.JPG)
These are the logs for my heroku app logs

**Comment by laurenceputra** [comment]
do you have a URL and test accounts?

or can you try it again? and give me your full URL?

**Comment by AirGuitar** [comment]
yea i have my site's url and the test accounts

Url - https://airguitar.herokuapp.com/

Test account
sandbox acc - airguitar.cc-facilitator@gmail.com/airguitar.cc-buyer@gmail.com

just tried it again and it didnt work :/

**Comment by laurenceputra** [comment]
I was just able to complete a checkout on your page

https://airguitar.herokuapp.com/payment/execute?token=EC-9X4607542N259351S

Response
{"status":"success","data":{"id":"I-68RF6JP0UJ74","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/billing-agreements/I-68RF6JP0UJ74","rel":"self","method":"GET"}],"httpStatusCode":200}}

What is the country of the buyer account?

**Comment by AirGuitar** [comment]
US haha

**Comment by laurenceputra** [comment]
try Singapore? I think the law doesn't allow US buyers to transact in SGD

**Comment by AirGuitar** [comment]
I see SUCCESS!! Anyway, so my firebase is just to store my plans is it? and the transaction currently can only be seen through the notification site at the sandbox?

**Comment by laurenceputra** [comment]
that's good to hear :)

firebase can be used to store the transactions too, but you will have to define how you are going to store the users, and how you will be doing logins and all that first.

point me to your code when you have done an app, and I can advise you on how best to continue?

**Comment by AirGuitar** [comment]
Hahaha thanks man! uhhh anyway ya i just thought the firebase app i prepared would have done that also but nvm. Login's something my group don't know whether we want to implement yet anot for the assignment now we're just trying to implement the things taught into our page first haha.

Anyway if you remembered a few of us were nodding of during the class you taught 2 weeks ago, sorry about that, my whole group had FYP and we tonned through the entire night before haha Hope it didnt give you a bad impression of us haha!

**Comment by laurenceputra** [comment]
no worries :) I was a student once too :P 

on the topic of login, you'll need that to determine if the user has paid for your plan, and if you should continue providing the service to your user.

**Comment by AirGuitar** [comment]
Indeed, hmmm will discuss with my partner about it!

**Comment by laurenceputra** [comment]
alright, since this issue is resolved i'll close it. feel free to open a new issue when you need help :)
